"""empty message

Revision ID: 5e4062f91a1e
Revises: 0bb0b79e2a3a
Create Date: 2019-10-25 13:33:08.255597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e4062f91a1e'
down_revision = '0bb0b79e2a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.add_column('users', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('commision', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('credit_card', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('cv', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('middle_initial', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=25), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stars', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'stars')
    op.drop_column('users', 'salary')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'middle_initial')
    op.drop_column('users', 'cv')
    op.drop_column('users', 'credit_card')
    op.drop_column('users', 'commision')
    op.drop_column('users', 'address')
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    # ### end Alembic commands ###
